on:
  push:
    branches:
      - main

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Package
      run: |
        npm ci
        npm test
        npm run package
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git add dist/
        git commit -m "chore: Update dist" || echo "No changes to commit"
        git push origin HEAD:main
